import type { Airport } from "./types";

const AIRPORTS: Airport[] = [
  { icao: "LOWK", iata: "KLU", name: "Klagenfurt Airport", city: "Klagenfurt", country: "Austria", lat: 46.6425, lon: 14.3377, tz: "Europe/Vienna" },
  { icao: "LOWW", iata: "VIE", name: "Vienna International Airport", city: "Vienna", country: "Austria", lat: 48.1103, lon: 16.5697, tz: "Europe/Vienna" },
  { icao: "LOWI", iata: "INN", name: "Innsbruck Airport", city: "Innsbruck", country: "Austria", lat: 47.2602, lon: 11.344, tz: "Europe/Vienna" },
  { icao: "LOWS", iata: "SZG", name: "Salzburg Airport W. A. Mozart", city: "Salzburg", country: "Austria", lat: 47.7933, lon: 13.0043, tz: "Europe/Vienna" },
  { icao: "LOWL", iata: "LNZ", name: "Linz Airport Blue Danube", city: "Linz", country: "Austria", lat: 48.2354, lon: 14.1881, tz: "Europe/Vienna" },
  { icao: "LOWG", iata: "GRZ", name: "Graz Airport", city: "Graz", country: "Austria", lat: 46.9911, lon: 15.4396, tz: "Europe/Vienna" },
  { icao: "EBBR", iata: "BRU", name: "Brussels Airport", city: "Brussels", country: "Belgium", lat: 50.9014, lon: 4.4844, tz: "Europe/Brussels" },
  { icao: "EBCI", iata: "CRL", name: "Brussels South Charleroi Airport", city: "Charleroi", country: "Belgium", lat: 50.462, lon: 4.4596, tz: "Europe/Brussels" },
  { icao: "EBLG", iata: "LGG", name: "Liège Airport", city: "Liège", country: "Belgium", lat: 50.6386, lon: 5.4439, tz: "Europe/Brussels" },
  { icao: "EBOS", iata: "OST", name: "Ostend-Bruges International Airport", city: "Ostend", country: "Belgium", lat: 51.1998, lon: 2.8747, tz: "Europe/Brussels" },
  { icao: "LQSA", iata: "SJJ", name: "Sarajevo International Airport", city: "Sarajevo", country: "Bosnia and Herzegovina", lat: 43.8246, lon: 18.3315, tz: "Europe/Sarajevo" },
  { icao: "LQBK", iata: "BNX", name: "Banja Luka International Airport", city: "Banja Luka", country: "Bosnia and Herzegovina", lat: 44.9414, lon: 17.2975, tz: "Europe/Sarajevo" },
  { icao: "LQMO", iata: "OMO", name: "Mostar Airport", city: "Mostar", country: "Bosnia and Herzegovina", lat: 43.2825, lon: 17.8461, tz: "Europe/Sarajevo" },
  { icao: "LQTZ", iata: "TZL", name: "Tuzla International Airport", city: "Tuzla", country: "Bosnia and Herzegovina", lat: 44.4599, lon: 18.7236, tz: "Europe/Sarajevo" },
  { icao: "LBSF", iata: "SOF", name: "Sofia Airport", city: "Sofia", country: "Bulgaria", lat: 42.6964, lon: 23.4177, tz: "Europe/Sofia" },
  { icao: "LBBG", iata: "BOJ", name: "Burgas Airport", city: "Burgas", country: "Bulgaria", lat: 42.5699, lon: 27.5152, tz: "Europe/Sofia" },
  { icao: "LBPD", iata: "PDV", name: "Plovdiv Airport", city: "Plovdiv", country: "Bulgaria", lat: 42.0678, lon: 24.8508, tz: "Europe/Sofia" },
  { icao: "LBWN", iata: "VAR", name: "Varna Airport", city: "Varna", country: "Bulgaria", lat: 43.2321, lon: 27.8251, tz: "Europe/Sofia" },
  { icao: "LDZA", iata: "ZAG", name: "Zagreb Franjo Tuđman Airport", city: "Zagreb", country: "Croatia", lat: 45.7429, lon: 16.0688, tz: "Europe/Zagreb" },
  { icao: "LDSP", iata: "SPU", name: "Split Airport", city: "Split", country: "Croatia", lat: 43.5389, lon: 16.298, tz: "Europe/Zagreb" },
  { icao: "LDDU", iata: "DBV", name: "Dubrovnik Airport", city: "Dubrovnik", country: "Croatia", lat: 42.5622, lon: 18.2655, tz: "Europe/Zagreb" },
  { icao: "LDRI", iata: "RJK", name: "Rijeka Airport", city: "Rijeka", country: "Croatia", lat: 45.2164, lon: 14.5709, tz: "Europe/Zagreb" },
  { icao: "LDPL", iata: "PUY", name: "Pula Airport", city: "Pula", country: "Croatia", lat: 44.8935, lon: 13.9222, tz: "Europe/Zagreb" },
  { icao: "LDZD", iata: "ZAD", name: "Zadar Airport", city: "Zadar", country: "Croatia", lat: 44.097, lon: 15.3536, tz: "Europe/Zagreb" },
  { icao: "LDOS", iata: "OSI", name: "Osijek Airport", city: "Osijek", country: "Croatia", lat: 45.4624, lon: 18.8113, tz: "Europe/Zagreb" },
  { icao: "LCLK", iata: "LCA", name: "Larnaca International Airport", city: "Larnaca", country: "Cyprus", lat: 34.8751, lon: 33.6249, tz: "Asia/Nicosia" },
  { icao: "LCPH", iata: "PFO", name: "Paphos Airport", city: "Paphos", country: "Cyprus", lat: 34.718, lon: 32.4857, tz: "Asia/Nicosia" },
  { icao: "LKPR", iata: "PRG", name: "Václav Havel Airport Prague", city: "Prague", country: "Czech Republic", lat: 50.1009, lon: 14.2599, tz: "Europe/Prague" },
  { icao: "LKMT", iata: "OSR", name: "Ostrava Leoš Janáček Airport", city: "Ostrava", country: "Czech Republic", lat: 49.6963, lon: 18.1111, tz: "Europe/Prague" },
  { icao: "LKPD", iata: "PED", name: "Pardubice Airport", city: "Pardubice", country: "Czech Republic", lat: 50.015, lon: 15.7398, tz: "Europe/Prague" },
  { icao: "LKBE", iata: "BRQ", name: "Brno-Tuřany Airport", city: "Brno", country: "Czech Republic", lat: 49.7408, lon: 14.6447, tz: "Europe/Prague" },
  { icao: "LKKV", iata: "KVD", name: "Karlovy Vary Airport", city: "Karlovy Vary", country: "Czech Republic", lat: 50.203, lon: 12.915, tz: "Europe/Prague" },
  { icao: "EKCH", iata: "CPH", name: "Copenhagen Airport Kastrup", city: "Copenhagen", country: "Denmark", lat: 55.6179, lon: 12.656, tz: "Europe/Copenhagen" },
  { icao: "EKBI", iata: "BLL", name: "Billund Airport", city: "Billund", country: "Denmark", lat: 55.7403, lon: 9.157, tz: "Europe/Copenhagen" },
  { icao: "EKYT", iata: "AAL", name: "Aalborg Airport", city: "Aalborg", country: "Denmark", lat: 57.0948, lon: 9.8499, tz: "Europe/Copenhagen" },
  { icao: "EKRN", iata: "RNN", name: "Bornholm Airport", city: "Bornholm", country: "Denmark", lat: 55.0633, lon: 14.7596, tz: "Europe/Copenhagen" },
  { icao: "EKVG", iata: "FAE", name: "Vágar Airport", city: "Faroe Islands", country: "Denmark", lat: 62.0633, lon: -7.2758, tz: "Atlantic/Faroe" },
  { icao: "EETN", iata: "TLL", name: "Tallinn Airport", city: "Tallinn", country: "Estonia", lat: 59.4132, lon: 24.8326, tz: "Europe/Tallinn" },
  { icao: "EEPU", iata: "EPU", name: "Pärnu Airport", city: "Pärnu", country: "Estonia", lat: 58.419, lon: 24.4728, tz: "Europe/Tallinn" },
  { icao: "EEKA", iata: "URE", name: "Kuressaare Airport", city: "Kuressaare", country: "Estonia", lat: 58.9908, lon: 22.8307, tz: "Europe/Tallinn" },
  { icao: "EFHK", iata: "HEL", name: "Helsinki-Vantaa Airport", city: "Helsinki", country: "Finland", lat: 60.3184, lon: 24.9633, tz: "Europe/Helsinki" },
  { icao: "EFTP", iata: "TMP", name: "Tampere-Pirkkala Airport", city: "Tampere", country: "Finland", lat: 61.4141, lon: 23.6044, tz: "Europe/Helsinki" },
  { icao: "EFOU", iata: "OUL", name: "Oulu Airport", city: "Oulu", country: "Finland", lat: 64.9301, lon: 25.3546, tz: "Europe/Helsinki" },
  { icao: "EFTU", iata: "TKU", name: "Turku Airport", city: "Turku", country: "Finland", lat: 60.5141, lon: 22.2628, tz: "Europe/Helsinki" },
  { icao: "EFRO", iata: "RVN", name: "Rovaniemi Airport", city: "Rovaniemi", country: "Finland", lat: 66.5633, lon: 25.8298, tz: "Europe/Helsinki" },
  { icao: "EFKT", iata: "KTT", name: "Kittilä Airport", city: "Kittilä", country: "Finland", lat: 67.701, lon: 24.8468, tz: "Europe/Helsinki" },
  { icao: "EFKU", iata: "KUO", name: "Kuopio Airport", city: "Kuopio", country: "Finland", lat: 63.0071, lon: 27.7978, tz: "Europe/Helsinki" },
  { icao: "EFJY", iata: "JYV", name: "Jyväskylä Airport", city: "Jyväskylä", country: "Finland", lat: 62.3995, lon: 25.6783, tz: "Europe/Helsinki" },
  { icao: "EFMA", iata: "MHQ", name: "Mariehamn Airport", city: "Mariehamn", country: "Finland", lat: 60.1222, lon: 19.8982, tz: "Europe/Helsinki" },
  { icao: "EFIV", iata: "IVL", name: "Ivalo Airport", city: "Ivalo", country: "Finland", lat: 68.6073, lon: 27.4053, tz: "Europe/Helsinki" },
  { icao: "EFJO", iata: "JOE", name: "Joensuu Airport", city: "Joensuu", country: "Finland", lat: 62.6588, lon: 29.6194, tz: "Europe/Helsinki" },
  { icao: "EFVA", iata: "VAA", name: "Vaasa Airport", city: "Vaasa", country: "Finland", lat: 63.0502, lon: 21.7625, tz: "Europe/Helsinki" },
  { icao: "EFLP", iata: "LPP", name: "Lappeenranta Airport", city: "Lappeenranta", country: "Finland", lat: 61.0446, lon: 28.1447, tz: "Europe/Helsinki" },
  { icao: "EFKE", iata: "KEM", name: "Kemi-Tornio Airport", city: "Kemi", country: "Finland", lat: 65.7787, lon: 24.5821, tz: "Europe/Helsinki" },
  { icao: "LFPG", iata: "CDG", name: "Charles de Gaulle Airport", city: "Paris", country: "France", lat: 49.009, lon: 2.5541, tz: "Europe/Paris" },
  { icao: "LFPO", iata: "ORY", name: "Paris Orly Airport", city: "Paris", country: "France", lat: 48.7295, lon: 2.359, tz: "Europe/Paris" },
  { icao: "LFMN", iata: "NCE", name: "Nice Côte d'Azur Airport", city: "Nice", country: "France", lat: 43.6584, lon: 7.2159, tz: "Europe/Paris" },
  { icao: "LFLL", iata: "LYS", name: "Lyon-Saint Exupéry Airport", city: "Lyon", country: "France", lat: 45.726, lon: 5.0901, tz: "Europe/Paris" },
  { icao: "LFRS", iata: "NTE", name: "Nantes Atlantique Airport", city: "Nantes", country: "France", lat: 47.1532, lon: -1.6107, tz: "Europe/Paris" },
  { icao: "LFBD", iata: "BOD", name: "Bordeaux–Mérignac Airport", city: "Bordeaux", country: "France", lat: 44.8287, lon: -0.7154, tz: "Europe/Paris" },
  { icao: "LFML", iata: "MRS", name: "Marseille Provence Airport", city: "Marseille", country: "France", lat: 43.4381, lon: 5.2125, tz: "Europe/Paris" },
  { icao: "LFBO", iata: "TLS", name: "Toulouse-Blagnac Airport", city: "Toulouse", country: "France", lat: 43.6291, lon: 1.3638, tz: "Europe/Paris" },
  { icao: "LFST", iata: "SXB", name: "Strasbourg Airport", city: "Strasbourg", country: "France", lat: 48.5383, lon: 7.6282, tz: "Europe/Paris" },
  { icao: "LFSB", iata: "BSL", name: "EuroAirport Basel-Mulhouse-Freiburg", city: "Basel", country: "France", lat: 47.6007, lon: 7.5211, tz: "Europe/Paris" },
  { icao: "LFRB", iata: "BES", name: "Brest Bretagne Airport", city: "Brest", country: "France", lat: 48.4479, lon: -4.4185, tz: "Europe/Paris" },
  { icao: "LFMT", iata: "MPL", name: "Montpellier-Méditerranée Airport", city: "Montpellier", country: "France", lat: 43.5762, lon: 3.963, tz: "Europe/Paris" },
  { icao: "LFQQ", iata: "LIL", name: "Lille Airport", city: "Lille", country: "France", lat: 50.5666, lon: 3.1024, tz: "Europe/Paris" },
  { icao: "LFRN", iata: "RNS", name: "Rennes-Saint-Jacques Airport", city: "Rennes", country: "France", lat: 48.0695, lon: -1.7348, tz: "Europe/Paris" },
  { icao: "LFKJ", iata: "AJA", name: "Ajaccio Napoléon Bonaparte Airport", city: "Ajaccio", country: "France", lat: 41.9236, lon: 8.8029, tz: "Europe/Paris" },
  { icao: "LFKB", iata: "BIA", name: "Bastia-Poretta Airport", city: "Bastia", country: "France", lat: 42.5527, lon: 9.4837, tz: "Europe/Paris" },
  { icao: "LFMK", iata: "CCF", name: "Carcassonne Airport", city: "Carcassonne", country: "France", lat: 43.216, lon: 2.3063, tz: "Europe/Paris" },
  { icao: "LFTH", iata: "TLN", name: "Toulon-Hyères Airport", city: "Toulon", country: "France", lat: 43.0973, lon: 6.146, tz: "Europe/Paris" },
  { icao: "LFBT", iata: "LDE", name: "Tarbes-Lourdes-Pyrénées Airport", city: "Tarbes", country: "France", lat: 43.1787, lon: -0.0064, tz: "Europe/Paris" },
  { icao: "LFBZ", iata: "BIQ", name: "Biarritz Pays Basque Airport", city: "Biarritz", country: "France", lat: 43.4684, lon: -1.5232, tz: "Europe/Paris" },
  { icao: "LFMH", iata: "EBU", name: "Saint-Étienne Bouthéon Airport", city: "Saint-Étienne", country: "France", lat: 45.5406, lon: 4.2964, tz: "Europe/Paris" },
  { icao: "LFCR", iata: "RDZ", name: "Rodez-Aveyron Airport", city: "Rodez", country: "France", lat: 44.4079, lon: 2.4827, tz: "Europe/Paris" },
  { icao: "LFJL", iata: "ETZ", name: "Metz-Nancy-Lorraine Airport", city: "Metz", country: "France", lat: 48.9821, lon: 6.2513, tz: "Europe/Paris" },
  { icao: "LFRH", iata: "LRT", name: "Lorient South Brittany Airport", city: "Lorient", country: "France", lat: 47.7606, lon: -3.44, tz: "Europe/Paris" },
  { icao: "LFRQ", iata: "UIP", name: "Quimper-Cornouaille Airport", city: "Quimper", country: "France", lat: 47.973, lon: -4.1697, tz: "Europe/Paris" },
  { icao: "LFOH", iata: "LEH", name: "Le Havre Octeville Airport", city: "Le Havre", country: "France", lat: 49.534, lon: 0.0884, tz: "Europe/Paris" },
  { icao: "EDDF", iata: "FRA", name: "Frankfurt Airport", city: "Frankfurt", country: "Germany", lat: 50.0267, lon: 8.5584, tz: "Europe/Berlin" },
  { icao: "EDDM", iata: "MUC", name: "Munich Airport", city: "Munich", country: "Germany", lat: 48.3538, lon: 11.7861, tz: "Europe/Berlin" },
  { icao: "EDDB", iata: "BER", name: "Berlin Brandenburg Airport", city: "Berlin", country: "Germany", lat: 52.3617, lon: 13.5023, tz: "Europe/Berlin" },
  { icao: "EDDL", iata: "DUS", name: "Düsseldorf Airport", city: "Düsseldorf", country: "Germany", lat: 51.2895, lon: 6.7668, tz: "Europe/Berlin" },
  { icao: "EDDC", iata: "DRS", name: "Dresden Airport", city: "Dresden", country: "Germany", lat: 51.1341, lon: 13.7678, tz: "Europe/Berlin" },
  { icao: "EDDE", iata: "ERF", name: "Erfurt-Weimar Airport", city: "Erfurt", country: "Germany", lat: 50.9783, lon: 10.9607, tz: "Europe/Berlin" },
  { icao: "EDDH", iata: "HAM", name: "Hamburg Airport", city: "Hamburg", country: "Germany", lat: 53.6304, lon: 9.9882, tz: "Europe/Berlin" },
  { icao: "EDDK", iata: "CGN", name: "Cologne Bonn Airport", city: "Cologne", country: "Germany", lat: 50.8659, lon: 7.1427, tz: "Europe/Berlin" },
  { icao: "EDDP", iata: "LEJ", name: "Leipzig/Halle Airport", city: "Leipzig", country: "Germany", lat: 51.4207, lon: 12.2327, tz: "Europe/Berlin" },
  { icao: "EDDS", iata: "STR", name: "Stuttgart Airport", city: "Stuttgart", country: "Germany", lat: 48.6899, lon: 9.222, tz: "Europe/Berlin" },
  { icao: "EDDG", iata: "FMO", name: "Münster Osnabrück Airport", city: "Münster", country: "Germany", lat: 52.1338, lon: 7.6885, tz: "Europe/Berlin" },
  { icao: "EDDN", iata: "NUE", name: "Nuremberg Airport", city: "Nuremberg", country: "Germany", lat: 49.4987, lon: 11.0781, tz: "Europe/Berlin" },
  { icao: "EDDR", iata: "SCN", name: "Saarbrücken Airport", city: "Saarbrücken", country: "Germany", lat: 49.2145, lon: 7.1097, tz: "Europe/Berlin" },
  { icao: "EDDW", iata: "BRE", name: "Bremen Airport", city: "Bremen", country: "Germany", lat: 53.0468, lon: 8.7893, tz: "Europe/Berlin" },
  { icao: "EDLW", iata: "DTM", name: "Dortmund Airport", city: "Dortmund", country: "Germany", lat: 51.5183, lon: 7.6122, tz: "Europe/Berlin" },
  { icao: "EDLP", iata: "PAD", name: "Paderborn Lippstadt Airport", city: "Paderborn", country: "Germany", lat: 51.6125, lon: 8.6175, tz: "Europe/Berlin" },
  { icao: "EDLV", iata: "NRN", name: "Weeze Airport", city: "Weeze", country: "Germany", lat: 51.6014, lon: 6.1412, tz: "Europe/Berlin" },
  { icao: "EDNY", iata: "FDH", name: "Friedrichshafen Airport", city: "Friedrichshafen", country: "Germany", lat: 47.6713, lon: 9.5115, tz: "Europe/Berlin" },
  { icao: "EDSB", iata: "FKB", name: "Karlsruhe/Baden-Baden Airport", city: "Karlsruhe", country: "Germany", lat: 48.7794, lon: 8.0805, tz: "Europe/Berlin" },
  { icao: "EDFH", iata: "HHN", name: "Frankfurt Hahn Airport", city: "Hahn", country: "Germany", lat: 49.9464, lon: 7.2617, tz: "Europe/Berlin" },
  { icao: "LXGB", iata: "GIB", name: "Gibraltar Airport", city: "Gibraltar", country: "Gibraltar", lat: 36.1517, lon: -5.3498, tz: "Europe/Gibraltar" },
  { icao: "LGAV", iata: "ATH", name: "Athens Eleftherios Venizelos Airport", city: "Athens", country: "Greece", lat: 37.9364, lon: 23.9445, tz: "Europe/Athens" },
  { icao: "LGTS", iata: "SKG", name: "Thessaloniki Macedonia Airport", city: "Thessaloniki", country: "Greece", lat: 40.5193, lon: 22.97, tz: "Europe/Athens" },
  { icao: "LGIR", iata: "HER", name: "Heraklion Nikos Kazantzakis Airport", city: "Heraklion", country: "Greece", lat: 35.3397, lon: 25.1803, tz: "Europe/Athens" },
  { icao: "LGKR", iata: "CFU", name: "Corfu Ioannis Kapodistrias Airport", city: "Corfu", country: "Greece", lat: 39.6014, lon: 19.9122, tz: "Europe/Athens" },
  { icao: "LGZA", iata: "ZTH", name: "Zakynthos International Airport", city: "Zakynthos", country: "Greece", lat: 37.7509, lon: 20.8843, tz: "Europe/Athens" },
  { icao: "LGRP", iata: "RHO", name: "Rhodes Diagoras Airport", city: "Rhodes", country: "Greece", lat: 36.4054, lon: 28.0862, tz: "Europe/Athens" },
  { icao: "LGKO", iata: "KGS", name: "Kos Airport", city: "Kos", country: "Greece", lat: 36.7945, lon: 27.0911, tz: "Europe/Athens" },
  { icao: "LGSA", iata: "CHQ", name: "Chania International Airport", city: "Chania", country: "Greece", lat: 35.5312, lon: 24.1507, tz: "Europe/Athens" },
  { icao: "LGSM", iata: "SMI", name: "Samos Airport", city: "Samos", country: "Greece", lat: 37.69, lon: 26.9117, tz: "Europe/Athens" },
  { icao: "LGKF", iata: "EFL", name: "Kefalonia Airport", city: "Kefalonia", country: "Greece", lat: 38.1201, lon: 20.5005, tz: "Europe/Athens" },
  { icao: "LGMK", iata: "JMK", name: "Mykonos Airport", city: "Mykonos", country: "Greece", lat: 37.4351, lon: 25.3481, tz: "Europe/Athens" },
  { icao: "LGSR", iata: "JTR", name: "Santorini Airport", city: "Santorini", country: "Greece", lat: 36.4, lon: 25.4786, tz: "Europe/Athens" },
  { icao: "LGKL", iata: "KLX", name: "Kalamata Airport", city: "Kalamata", country: "Greece", lat: 37.0683, lon: 22.0255, tz: "Europe/Athens" },
  { icao: "LGMT", iata: "MJT", name: "Mytilene Airport", city: "Lesbos", country: "Greece", lat: 39.0574, lon: 26.5986, tz: "Europe/Athens" },
  { icao: "LGKV", iata: "KVA", name: "Kavala International Airport", city: "Kavala", country: "Greece", lat: 40.9133, lon: 24.6192, tz: "Europe/Athens" },
  { icao: "LGIO", iata: "IOA", name: "Ioannina Airport", city: "Ioannina", country: "Greece", lat: 39.6964, lon: 20.8225, tz: "Europe/Athens" },
  { icao: "LGPZ", iata: "PVK", name: "Aktion National Airport", city: "Preveza", country: "Greece", lat: 38.9255, lon: 20.7653, tz: "Europe/Athens" },
  { icao: "LGAX", iata: "AXD", name: "Alexandroupoli Airport", city: "Alexandroupoli", country: "Greece", lat: 40.6511, lon: 22.4887, tz: "Europe/Athens" },
  { icao: "LGST", iata: "JSI", name: "Skiathos Airport", city: "Skiathos", country: "Greece", lat: 35.2161, lon: 26.1013, tz: "Europe/Athens" },
  { icao: "LHBP", iata: "BUD", name: "Budapest Liszt Ferenc International Airport", city: "Budapest", country: "Hungary", lat: 47.4302, lon: 19.2624, tz: "Europe/Budapest" },
  { icao: "LHDC", iata: "DEB", name: "Debrecen International Airport", city: "Debrecen", country: "Hungary", lat: 47.4895, lon: 21.6163, tz: "Europe/Budapest" },
  { icao: "BIKF", iata: "KEF", name: "Keflavik International Airport", city: "Reykjavik", country: "Iceland", lat: 63.985, lon: -22.6056, tz: "Atlantic/Reykjavik" },
  { icao: "BIRK", iata: "RKV", name: "Reykjavik City Airport", city: "Reykjavik", country: "Iceland", lat: 64.1287, lon: -21.9376, tz: "Atlantic/Reykjavik" },
  { icao: "BIAR", iata: "AEY", name: "Akureyri Airport", city: "Akureyri", country: "Iceland", lat: 65.6566, lon: -18.072, tz: "Atlantic/Reykjavik" },
  { icao: "BIEG", iata: "EGS", name: "Egilsstadir Airport", city: "Egilsstadir", country: "Iceland", lat: 65.2833, lon: -14.4014, tz: "Atlantic/Reykjavik" },
  { icao: "EIDW", iata: "DUB", name: "Dublin Airport", city: "Dublin", country: "Ireland", lat: 53.4287, lon: -6.2621, tz: "Europe/Dublin" },
  { icao: "EICK", iata: "ORK", name: "Cork Airport", city: "Cork", country: "Ireland", lat: 51.8413, lon: -8.4911, tz: "Europe/Dublin" },
  { icao: "EINN", iata: "SNN", name: "Shannon Airport", city: "Shannon", country: "Ireland", lat: 52.702, lon: -8.9248, tz: "Europe/Dublin" },
  { icao: "EIKN", iata: "NOC", name: "Ireland West Airport Knock", city: "Knock", country: "Ireland", lat: 53.9104, lon: -8.817, tz: "Europe/Dublin" },
  { icao: "EIDL", iata: "CFN", name: "Donegal Airport", city: "Donegal", country: "Ireland", lat: 55.0442, lon: -8.341, tz: "Europe/Dublin" },
  { icao: "EIKY", iata: "KIR", name: "Kerry Airport", city: "Kerry", country: "Ireland", lat: 52.1809, lon: -9.5238, tz: "Europe/Dublin" },
  { icao: "LIRF", iata: "FCO", name: "Leonardo da Vinci–Fiumicino Airport", city: "Rome", country: "Italy", lat: 41.8045, lon: 12.252, tz: "Europe/Rome" },
  { icao: "LIML", iata: "LIN", name: "Milan Linate Airport", city: "Milan", country: "Italy", lat: 45.4451, lon: 9.2767, tz: "Europe/Rome" },
  { icao: "LIMC", iata: "MXP", name: "Milan Malpensa Airport", city: "Milan", country: "Italy", lat: 45.6306, lon: 8.7281, tz: "Europe/Rome" },
  { icao: "LIPE", iata: "BLQ", name: "Bologna Guglielmo Marconi Airport", city: "Bologna", country: "Italy", lat: 44.5354, lon: 11.2887, tz: "Europe/Rome" },
  { icao: "LIPZ", iata: "VCE", name: "Venice Marco Polo Airport", city: "Venice", country: "Italy", lat: 45.5053, lon: 12.3519, tz: "Europe/Rome" },
  { icao: "LIMJ", iata: "GOA", name: "Genoa Cristoforo Colombo Airport", city: "Genoa", country: "Italy", lat: 44.412, lon: 8.8407, tz: "Europe/Rome" },
  { icao: "LICC", iata: "CTA", name: "Catania Fontanarossa Airport", city: "Catania", country: "Italy", lat: 37.4668, lon: 15.0664, tz: "Europe/Rome" },
  { icao: "LICJ", iata: "PMO", name: "Palermo Falcone Borsellino Airport", city: "Palermo", country: "Italy", lat: 38.176, lon: 13.091, tz: "Europe/Rome" },
  { icao: "LIBD", iata: "BRI", name: "Bari Karol Wojtyla Airport", city: "Bari", country: "Italy", lat: 41.1389, lon: 16.7606, tz: "Europe/Rome" },
  { icao: "LIBP", iata: "PSR", name: "Pescara International Airport", city: "Pescara", country: "Italy", lat: 42.4311, lon: 14.183, tz: "Europe/Rome" },
  { icao: "LIRA", iata: "CIA", name: "Rome Ciampino Airport", city: "Rome", country: "Italy", lat: 41.7988, lon: 12.5953, tz: "Europe/Rome" },
  { icao: "LIRQ", iata: "FLR", name: "Florence Amerigo Vespucci Airport", city: "Florence", country: "Italy", lat: 43.8086, lon: 11.2028, tz: "Europe/Rome" },
  { icao: "LIMF", iata: "TRN", name: "Turin Airport", city: "Turin", country: "Italy", lat: 45.2008, lon: 7.6496, tz: "Europe/Rome" },
  { icao: "LICA", iata: "SUF", name: "Lamezia Terme International Airport", city: "Lamezia Terme", country: "Italy", lat: 38.9062, lon: 16.246, tz: "Europe/Rome" },
  { icao: "LICR", iata: "REG", name: "Reggio Calabria Airport", city: "Reggio Calabria", country: "Italy", lat: 38.0712, lon: 15.6516, tz: "Europe/Rome" },
  { icao: "LIPQ", iata: "TRS", name: "Trieste Ronchi dei Legionari Airport", city: "Trieste", country: "Italy", lat: 45.8279, lon: 13.4667, tz: "Europe/Rome" },
  { icao: "LIEA", iata: "AHO", name: "Alghero Riviera del Corallo Airport", city: "Alghero", country: "Italy", lat: 40.6321, lon: 8.2908, tz: "Europe/Rome" },
  { icao: "LIEE", iata: "CAG", name: "Cagliari Elmas Airport", city: "Cagliari", country: "Italy", lat: 39.2515, lon: 9.0543, tz: "Europe/Rome" },
  { icao: "LIEO", iata: "OLB", name: "Olbia Costa Smeralda Airport", city: "Olbia", country: "Italy", lat: 40.899, lon: 9.5185, tz: "Europe/Rome" },
  { icao: "LIBR", iata: "BDS", name: "Brindisi Salento Airport", city: "Brindisi", country: "Italy", lat: 40.6576, lon: 17.947, tz: "Europe/Rome" },
  { icao: "LIPX", iata: "VRN", name: "Verona Villafranca Airport", city: "Verona", country: "Italy", lat: 45.395, lon: 10.8873, tz: "Europe/Rome" },
  { icao: "LIPH", iata: "TSF", name: "Treviso Airport", city: "Treviso", country: "Italy", lat: 45.6484, lon: 12.1944, tz: "Europe/Rome" },
  { icao: "LIPY", iata: "AOI", name: "Marche Airport Ancona", city: "Ancona", country: "Italy", lat: 43.6163, lon: 13.3623, tz: "Europe/Rome" },
  { icao: "LIRN", iata: "NAP", name: "Naples International Airport", city: "Naples", country: "Italy", lat: 40.886, lon: 14.2908, tz: "Europe/Rome" },
  { icao: "LIRP", iata: "PSA", name: "Pisa Galileo Galilei Airport", city: "Pisa", country: "Italy", lat: 43.6839, lon: 10.3927, tz: "Europe/Rome" },
  { icao: "LICD", iata: "LMP", name: "Lampedusa Airport", city: "Lampedusa", country: "Italy", lat: 35.4979, lon: 12.6181, tz: "Europe/Rome" },
  { icao: "LICG", iata: "PNL", name: "Pantelleria Airport", city: "Pantelleria", country: "Italy", lat: 36.8165, lon: 11.9689, tz: "Europe/Rome" },
  { icao: "LIPO", iata: "VBS", name: "Brescia Gabriele D'Annunzio Airport", city: "Brescia", country: "Italy", lat: 45.4289, lon: 10.3306, tz: "Europe/Rome" },
  { icao: "LIPK", iata: "FRL", name: "Forli Airport", city: "Forlì", country: "Italy", lat: 44.1948, lon: 12.0701, tz: "Europe/Rome" },
  { icao: "LIRZ", iata: "PEG", name: "Perugia San Francesco d'Assisi Airport", city: "Perugia", country: "Italy", lat: 43.0959, lon: 12.5132, tz: "Europe/Rome" },
  { icao: "BKPR", iata: "PRN", name: "Pristina Adem Jashari International Airport", city: "Pristina", country: "Kosovo", lat: 42.5728, lon: 21.0358, tz: "Europe/Belgrade" },
  { icao: "EVRA", iata: "RIX", name: "Riga International Airport", city: "Riga", country: "Latvia", lat: 56.9208, lon: 23.9707, tz: "Europe/Riga" },
  { icao: "EVLA", iata: "LPX", name: "Liepāja International Airport", city: "Liepāja", country: "Latvia", lat: 56.5175, lon: 21.0969, tz: "Europe/Riga" },
  { icao: "EYVI", iata: "VNO", name: "Vilnius Airport", city: "Vilnius", country: "Lithuania", lat: 54.6341, lon: 25.2858, tz: "Europe/Vilnius" },
  { icao: "EYKA", iata: "KUN", name: "Kaunas Airport", city: "Kaunas", country: "Lithuania", lat: 54.964, lon: 24.0858, tz: "Europe/Vilnius" },
  { icao: "EYPA", iata: "PLQ", name: "Palanga International Airport", city: "Palanga", country: "Lithuania", lat: 55.9732, lon: 21.0939, tz: "Europe/Vilnius" },
  { icao: "ELLX", iata: "LUX", name: "Luxembourg Findel Airport", city: "Luxembourg", country: "Luxembourg", lat: 49.6268, lon: 6.2121, tz: "Europe/Luxembourg" },
  { icao: "LMML", iata: "MLA", name: "Malta International Airport", city: "Valletta", country: "Malta", lat: 35.8459, lon: 14.4915, tz: "Europe/Malta" },
  { icao: "LUKK", iata: "KIV", name: "Chișinău International Airport", city: "Chisinau", country: "Moldova", lat: 46.9277, lon: 28.9317, tz: "Europe/Chisinau" },
  { icao: "LYTV", iata: "TIV", name: "Tivat Airport", city: "Tivat", country: "Montenegro", lat: 42.4047, lon: 18.7233, tz: "Europe/Podgorica" },
  { icao: "LYPO", iata: "TGD", name: "Podgorica Airport", city: "Podgorica", country: "Montenegro", lat: 42.4223, lon: 19.291, tz: "Europe/Podgorica" },
  { icao: "EHAM", iata: "AMS", name: "Amsterdam Airport Schiphol", city: "Amsterdam", country: "Netherlands", lat: 52.3086, lon: 4.7639, tz: "Europe/Amsterdam" },
  { icao: "EHRD", iata: "RTM", name: "Rotterdam The Hague Airport", city: "Rotterdam", country: "Netherlands", lat: 51.9569, lon: 4.4372, tz: "Europe/Amsterdam" },
  { icao: "EHGG", iata: "GRQ", name: "Groningen Airport Eelde", city: "Groningen", country: "Netherlands", lat: 53.1191, lon: 6.5777, tz: "Europe/Amsterdam" },
  { icao: "EHMZ", iata: "MST", name: "Maastricht Aachen Airport", city: "Maastricht", country: "Netherlands", lat: 51.5122, lon: 3.7311, tz: "Europe/Amsterdam" },
  { icao: "EHEH", iata: "EIN", name: "Eindhoven Airport", city: "Eindhoven", country: "Netherlands", lat: 51.4501, lon: 5.3745, tz: "Europe/Amsterdam" },
  { icao: "LWSK", iata: "SKP", name: "Skopje Alexander the Great Airport", city: "Skopje", country: "North Macedonia", lat: 41.9581, lon: 21.6226, tz: "Europe/Skopje" },
  { icao: "LWOH", iata: "OHD", name: "Ohrid St. Paul the Apostle Airport", city: "Ohrid", country: "North Macedonia", lat: 41.18, lon: 20.7423, tz: "Europe/Skopje" },
  { icao: "ENGM", iata: "OSL", name: "Oslo Gardermoen Airport", city: "Oslo", country: "Norway", lat: 60.1939, lon: 11.1004, tz: "Europe/Oslo" },
  { icao: "ENBR", iata: "BGO", name: "Bergen Flesland Airport", city: "Bergen", country: "Norway", lat: 60.2934, lon: 5.2181, tz: "Europe/Oslo" },
  { icao: "ENVA", iata: "TRD", name: "Trondheim Vaernes Airport", city: "Trondheim", country: "Norway", lat: 63.4578, lon: 10.924, tz: "Europe/Oslo" },
  { icao: "ENBO", iata: "BOO", name: "Bodø Airport", city: "Bodø", country: "Norway", lat: 67.2692, lon: 14.3653, tz: "Europe/Oslo" },
  { icao: "ENTC", iata: "TOS", name: "Tromsø Airport", city: "Tromsø", country: "Norway", lat: 69.6833, lon: 18.9189, tz: "Europe/Oslo" },
  { icao: "ENZV", iata: "SVG", name: "Stavanger Sola Airport", city: "Stavanger", country: "Norway", lat: 58.8767, lon: 5.6378, tz: "Europe/Oslo" },
  { icao: "ENKR", iata: "KKN", name: "Kirkenes Høybuktmoen Airport", city: "Kirkenes", country: "Norway", lat: 69.7258, lon: 29.8913, tz: "Europe/Oslo" },
  { icao: "ENAL", iata: "AES", name: "Ålesund Vigra Airport", city: "Ålesund", country: "Norway", lat: 62.5604, lon: 6.1108, tz: "Europe/Oslo" },
  { icao: "ENCN", iata: "KRS", name: "Kristiansand Kjevik Airport", city: "Kristiansand", country: "Norway", lat: 58.2042, lon: 8.0854, tz: "Europe/Oslo" },
  { icao: "ENFL", iata: "FRO", name: "Florø Airport", city: "Florø", country: "Norway", lat: 61.5836, lon: 5.0247, tz: "Europe/Oslo" },
  { icao: "ENHF", iata: "HFT", name: "Hammerfest Airport", city: "Hammerfest", country: "Norway", lat: 70.6797, lon: 23.6686, tz: "Europe/Oslo" },
  { icao: "ENLU", iata: "LYR", name: "Svalbard Longyear Airport", city: "Longyearbyen", country: "Norway", lat: 59.298, lon: 9.132, tz: "Arctic/Longyearbyen" },
  { icao: "ENRA", iata: "MQN", name: "Mo i Rana Airport", city: "Mo i Rana", country: "Norway", lat: 66.3639, lon: 14.3014, tz: "Europe/Oslo" },
  { icao: "ENSG", iata: "SOG", name: "Sogndal Airport", city: "Sogndal", country: "Norway", lat: 61.1561, lon: 7.1378, tz: "Europe/Oslo" },
  { icao: "ENEV", iata: "EVE", name: "Harstad/Narvik Airport Evenes", city: "Harstad", country: "Norway", lat: 68.4913, lon: 16.6781, tz: "Europe/Oslo" },
  { icao: "ENNA", iata: "LKL", name: "Lakselv Banak Airport", city: "Lakselv", country: "Norway", lat: 70.0688, lon: 24.9735, tz: "Europe/Oslo" },
  { icao: "EPWA", iata: "WAW", name: "Warsaw Chopin Airport", city: "Warsaw", country: "Poland", lat: 52.1657, lon: 20.9671, tz: "Europe/Warsaw" },
  { icao: "EPKK", iata: "KRK", name: "Kraków John Paul II International Airport", city: "Kraków", country: "Poland", lat: 50.0777, lon: 19.7848, tz: "Europe/Warsaw" },
  { icao: "EPGD", iata: "GDN", name: "Gdańsk Lech Wałęsa Airport", city: "Gdańsk", country: "Poland", lat: 54.3776, lon: 18.4662, tz: "Europe/Warsaw" },
  { icao: "EPWR", iata: "WRO", name: "Wrocław Nicolaus Copernicus Airport", city: "Wrocław", country: "Poland", lat: 51.1037, lon: 16.8821, tz: "Europe/Warsaw" },
  { icao: "EPPO", iata: "POZ", name: "Poznań Ławica Airport", city: "Poznań", country: "Poland", lat: 52.4216, lon: 16.8234, tz: "Europe/Warsaw" },
  { icao: "EPKT", iata: "KTW", name: "Katowice International Airport", city: "Katowice", country: "Poland", lat: 50.476, lon: 19.0807, tz: "Europe/Warsaw" },
  { icao: "EPLL", iata: "LCJ", name: "Łódź Władysław Reymont Airport", city: "Łódź", country: "Poland", lat: 51.7219, lon: 19.3981, tz: "Europe/Warsaw" },
  { icao: "EPRZ", iata: "RZE", name: "Rzeszów-Jasionka Airport", city: "Rzeszów", country: "Poland", lat: 50.1098, lon: 22.0242, tz: "Europe/Warsaw" },
  { icao: "EPBY", iata: "BZG", name: "Bydgoszcz Paderewski Airport", city: "Bydgoszcz", country: "Poland", lat: 53.0968, lon: 17.9777, tz: "Europe/Warsaw" },
  { icao: "EPLU", iata: "LUZ", name: "Lublin Airport", city: "Lublin", country: "Poland", lat: 51.423, lon: 16.1962, tz: "Europe/Warsaw" },
  { icao: "EPSC", iata: "SZZ", name: "Szczecin-Goleniów Airport", city: "Szczecin", country: "Poland", lat: 53.5847, lon: 14.9022, tz: "Europe/Warsaw" },
  { icao: "LPPT", iata: "LIS", name: "Lisbon Humberto Delgado Airport", city: "Lisbon", country: "Portugal", lat: 38.7813, lon: -9.1359, tz: "Europe/Lisbon" },
  { icao: "LPPR", iata: "OPO", name: "Francisco Sá Carneiro Airport", city: "Porto", country: "Portugal", lat: 41.2481, lon: -8.6814, tz: "Europe/Lisbon" },
  { icao: "LPFR", iata: "FAO", name: "Faro Airport", city: "Faro", country: "Portugal", lat: 37.0159, lon: -7.9709, tz: "Europe/Lisbon" },
  { icao: "LPMA", iata: "FNC", name: "Madeira Airport", city: "Funchal", country: "Portugal", lat: 32.6978, lon: -16.7746, tz: "Atlantic/Madeira" },
  { icao: "LPPD", iata: "PDL", name: "João Paulo II Airport", city: "Ponta Delgada", country: "Portugal", lat: 37.7412, lon: -25.6979, tz: "Atlantic/Azores" },
  { icao: "LPLA", iata: "TER", name: "Lajes Field", city: "Terceira", country: "Portugal", lat: 38.7618, lon: -27.0908, tz: "Atlantic/Azores" },
  { icao: "LPHR", iata: "HOR", name: "Horta Airport", city: "Horta", country: "Portugal", lat: 38.5199, lon: -28.7159, tz: "Atlantic/Azores" },
  { icao: "LPAZ", iata: "SMA", name: "Santa Maria Airport", city: "Santa Maria", country: "Portugal", lat: 36.9714, lon: -25.1706, tz: "Atlantic/Azores" },
  { icao: "LPPI", iata: "PIX", name: "Pico Airport", city: "Pico Island", country: "Portugal", lat: 38.5543, lon: -28.4413, tz: "Atlantic/Azores" },
  { icao: "LPFL", iata: "FLW", name: "Flores Airport", city: "Flores Island", country: "Portugal", lat: 39.4553, lon: -31.1314, tz: "Atlantic/Azores" },
  { icao: "LROP", iata: "OTP", name: "Henri Coandă International Airport", city: "Bucharest", country: "Romania", lat: 44.5718, lon: 26.1033, tz: "Europe/Bucharest" },
  { icao: "LRCL", iata: "CLJ", name: "Cluj-Napoca International Airport", city: "Cluj-Napoca", country: "Romania", lat: 46.786, lon: 23.6857, tz: "Europe/Bucharest" },
  { icao: "LRTM", iata: "TGM", name: "Transylvania International Airport", city: "Târgu Mureș", country: "Romania", lat: 46.4677, lon: 24.4125, tz: "Europe/Bucharest" },
  { icao: "LRTR", iata: "TSR", name: "Timișoara Traian Vuia International Airport", city: "Timișoara", country: "Romania", lat: 45.8099, lon: 21.3379, tz: "Europe/Bucharest" },
  { icao: "LRIA", iata: "IAS", name: "Iași International Airport", city: "Iași", country: "Romania", lat: 47.1796, lon: 27.6214, tz: "Europe/Bucharest" },
  { icao: "LRBC", iata: "BCM", name: "Bacău George Enescu International Airport", city: "Bacău", country: "Romania", lat: 46.5219, lon: 26.9103, tz: "Europe/Bucharest" },
  { icao: "LROD", iata: "OMR", name: "Oradea International Airport", city: "Oradea", country: "Romania", lat: 47.0253, lon: 21.9025, tz: "Europe/Bucharest" },
  { icao: "LRSB", iata: "SBZ", name: "Sibiu International Airport", city: "Sibiu", country: "Romania", lat: 45.7858, lon: 24.0867, tz: "Europe/Bucharest" },
  { icao: "LRCK", iata: "CND", name: "Mihail Kogălniceanu International Airport", city: "Constanța", country: "Romania", lat: 44.3622, lon: 28.4883, tz: "Europe/Bucharest" },
  { icao: "LRSV", iata: "SCV", name: "Suceava Stefan cel Mare Airport", city: "Suceava", country: "Romania", lat: 47.6875, lon: 26.3541, tz: "Europe/Bucharest" },
  { icao: "LYBE", iata: "BEG", name: "Belgrade Nikola Tesla Airport", city: "Belgrade", country: "Serbia", lat: 44.8184, lon: 20.3091, tz: "Europe/Belgrade" },
  { icao: "LYNI", iata: "INI", name: "Niš Constantine the Great Airport", city: "Niš", country: "Serbia", lat: 43.3365, lon: 21.8562, tz: "Europe/Belgrade" },
  { icao: "LZIB", iata: "BTS", name: "Bratislava Milan Rastislav Štefánik Airport", city: "Bratislava", country: "Slovakia", lat: 48.1702, lon: 17.2127, tz: "Europe/Bratislava" },
  { icao: "LZKZ", iata: "KSC", name: "Košice International Airport", city: "Košice", country: "Slovakia", lat: 48.6631, lon: 21.2411, tz: "Europe/Bratislava" },
  { icao: "LJLJ", iata: "LJU", name: "Ljubljana Jože Pučnik Airport", city: "Ljubljana", country: "Slovenia", lat: 46.2237, lon: 14.4576, tz: "Europe/Ljubljana" },
  { icao: "LEMD", iata: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport", city: "Madrid", country: "Spain", lat: 40.4934, lon: -3.5722, tz: "Europe/Madrid" },
  { icao: "LEPA", iata: "PMI", name: "Palma de Mallorca Airport", city: "Palma de Mallorca", country: "Spain", lat: 39.5517, lon: 2.7388, tz: "Europe/Madrid" },
  { icao: "LEBL", iata: "BCN", name: "Barcelona El Prat Airport", city: "Barcelona", country: "Spain", lat: 41.2971, lon: 2.0785, tz: "Europe/Madrid" },
  { icao: "LEAL", iata: "ALC", name: "Alicante-Elche Airport", city: "Alicante", country: "Spain", lat: 38.2822, lon: -0.5582, tz: "Europe/Madrid" },
  { icao: "LEMG", iata: "AGP", name: "Málaga-Costa del Sol Airport", city: "Málaga", country: "Spain", lat: 36.6749, lon: -4.4991, tz: "Europe/Madrid" },
  { icao: "LEVX", iata: "VGO", name: "Vigo Airport", city: "Vigo", country: "Spain", lat: 42.2318, lon: -8.6268, tz: "Europe/Madrid" },
  { icao: "LEVC", iata: "VLC", name: "Valencia Airport", city: "Valencia", country: "Spain", lat: 39.4892, lon: -0.481, tz: "Europe/Madrid" },
  { icao: "LEZL", iata: "SVQ", name: "Seville Airport", city: "Seville", country: "Spain", lat: 37.418, lon: -5.8931, tz: "Europe/Madrid" },
  { icao: "LEBB", iata: "BIO", name: "Bilbao Airport", city: "Bilbao", country: "Spain", lat: 43.3011, lon: -2.9106, tz: "Europe/Madrid" },
  { icao: "LEXJ", iata: "SDR", name: "Santander Airport", city: "Santander", country: "Spain", lat: 43.4271, lon: -3.82, tz: "Europe/Madrid" },
  { icao: "LEAS", iata: "OVD", name: "Asturias Airport", city: "Asturias", country: "Spain", lat: 43.5636, lon: -6.0346, tz: "Europe/Madrid" },
  { icao: "LECO", iata: "LCG", name: "A Coruña Airport", city: "A Coruña", country: "Spain", lat: 43.3021, lon: -8.3773, tz: "Europe/Madrid" },
  { icao: "LEGR", iata: "GRX", name: "Federico García Lorca Granada-Jaén Airport", city: "Granada", country: "Spain", lat: 37.1887, lon: -3.7774, tz: "Europe/Madrid" },
  { icao: "LEAM", iata: "LEI", name: "Almería Airport", city: "Almería", country: "Spain", lat: 36.8439, lon: -2.3701, tz: "Europe/Madrid" },
  { icao: "LEMI", iata: "RMU", name: "Región de Murcia International Airport", city: "Murcia", country: "Spain", lat: 37.8029, lon: -1.1249, tz: "Europe/Madrid" },
  { icao: "LERS", iata: "REU", name: "Reus Airport", city: "Reus", country: "Spain", lat: 41.1475, lon: 1.1684, tz: "Europe/Madrid" },
  { icao: "LEIB", iata: "IBZ", name: "Ibiza Airport", city: "Ibiza", country: "Spain", lat: 38.8729, lon: 1.3731, tz: "Europe/Madrid" },
  { icao: "LEMH", iata: "MAH", name: "Menorca Airport", city: "Menorca", country: "Spain", lat: 39.8626, lon: 4.2187, tz: "Europe/Madrid" },
  { icao: "GCFV", iata: "FUE", name: "Fuerteventura Airport", city: "Fuerteventura", country: "Spain", lat: 28.4527, lon: -13.8638, tz: "Atlantic/Canary" },
  { icao: "GCLP", iata: "LPA", name: "Gran Canaria Airport", city: "Las Palmas", country: "Spain", lat: 27.9319, lon: -15.3866, tz: "Atlantic/Canary" },
  { icao: "GCTS", iata: "TFS", name: "Tenerife South Airport", city: "Tenerife", country: "Spain", lat: 28.0445, lon: -16.5725, tz: "Atlantic/Canary" },
  { icao: "GCXO", iata: "TFN", name: "Tenerife North Airport", city: "Tenerife", country: "Spain", lat: 28.4828, lon: -16.3417, tz: "Atlantic/Canary" },
  { icao: "GCRR", iata: "ACE", name: "Lanzarote Airport", city: "Lanzarote", country: "Spain", lat: 28.9455, lon: -13.6052, tz: "Atlantic/Canary" },
  { icao: "GCLA", iata: "SPC", name: "La Palma Airport", city: "La Palma", country: "Spain", lat: 28.6265, lon: -17.7556, tz: "Atlantic/Canary" },
  { icao: "GCHI", iata: "VDE", name: "El Hierro Airport", city: "El Hierro", country: "Spain", lat: 27.8148, lon: -17.8871, tz: "Atlantic/Canary" },
  { icao: "GCGO", iata: "GMZ", name: "La Gomera Airport", city: "La Gomera", country: "Spain", lat: 28.0972, lon: -17.1024, tz: "Atlantic/Canary" },
  { icao: "ESSA", iata: "ARN", name: "Stockholm Arlanda Airport", city: "Stockholm", country: "Sweden", lat: 59.6485, lon: 17.9288, tz: "Europe/Stockholm" },
  { icao: "ESKN", iata: "NYO", name: "Stockholm Skavsta Airport", city: "Stockholm", country: "Sweden", lat: 58.7897, lon: 16.9115, tz: "Europe/Stockholm" },
  { icao: "ESSD", iata: "BMA", name: "Stockholm Bromma Airport", city: "Stockholm", country: "Sweden", lat: 60.422, lon: 15.5152, tz: "Europe/Stockholm" },
  { icao: "ESOW", iata: "VST", name: "Stockholm Västerås Airport", city: "Västerås", country: "Sweden", lat: 59.5894, lon: 16.6336, tz: "Europe/Stockholm" },
  { icao: "ESGG", iata: "GOT", name: "Gothenburg Landvetter Airport", city: "Gothenburg", country: "Sweden", lat: 57.6628, lon: 12.2798, tz: "Europe/Stockholm" },
  { icao: "ESMS", iata: "MMX", name: "Malmö Airport", city: "Malmö", country: "Sweden", lat: 55.5356, lon: 13.3763, tz: "Europe/Stockholm" },
  { icao: "ESPA", iata: "LLA", name: "Luleå Airport", city: "Luleå", country: "Sweden", lat: 65.5438, lon: 22.122, tz: "Europe/Stockholm" },
  { icao: "ESNU", iata: "UME", name: "Umeå Airport", city: "Umeå", country: "Sweden", lat: 63.7918, lon: 20.2828, tz: "Europe/Stockholm" },
  { icao: "ESNS", iata: "SDL", name: "Sundsvall-Timrå Airport", city: "Sundsvall", country: "Sweden", lat: 64.6248, lon: 21.0769, tz: "Europe/Stockholm" },
  { icao: "ESNZ", iata: "OSD", name: "Åre Östersund Airport", city: "Östersund", country: "Sweden", lat: 63.1935, lon: 14.5042, tz: "Europe/Stockholm" },
  { icao: "ESQO", iata: "GEV", name: "Gällivare Airport", city: "Gällivare", country: "Sweden", lat: 59.3866, lon: 15.9241, tz: "Europe/Stockholm" },
  { icao: "ESMQ", iata: "KLR", name: "Kalmar Airport", city: "Kalmar", country: "Sweden", lat: 56.6855, lon: 16.2876, tz: "Europe/Stockholm" },
  { icao: "ESMX", iata: "VXO", name: "Växjö Kronoberg Airport", city: "Växjö", country: "Sweden", lat: 56.9291, lon: 14.728, tz: "Europe/Stockholm" },
  { icao: "LSZH", iata: "ZRH", name: "Zurich Airport", city: "Zurich", country: "Switzerland", lat: 47.4581, lon: 8.5481, tz: "Europe/Zurich" },
  { icao: "LSGG", iata: "GVA", name: "Geneva Airport", city: "Geneva", country: "Switzerland", lat: 46.2381, lon: 6.109, tz: "Europe/Zurich" },
  { icao: "LTFM", iata: "IST", name: "Istanbul Airport", city: "Istanbul", country: "Turkey", lat: 41.2749, lon: 28.7321, tz: "Europe/Istanbul" },
  { icao: "LTFJ", iata: "SAW", name: "Istanbul Sabiha Gökçen Airport", city: "Istanbul", country: "Turkey", lat: 40.8986, lon: 29.3092, tz: "Europe/Istanbul" },
  { icao: "LTAI", iata: "AYT", name: "Antalya Airport", city: "Antalya", country: "Turkey", lat: 36.8987, lon: 30.8005, tz: "Europe/Istanbul" },
  { icao: "LTBS", iata: "DLM", name: "Dalaman Airport", city: "Dalaman", country: "Turkey", lat: 36.7131, lon: 28.7925, tz: "Europe/Istanbul" },
  { icao: "LTBJ", iata: "ADB", name: "Izmir Adnan Menderes Airport", city: "Izmir", country: "Turkey", lat: 38.2924, lon: 27.157, tz: "Europe/Istanbul" },
  { icao: "LTFE", iata: "BJV", name: "Milas-Bodrum Airport", city: "Bodrum", country: "Turkey", lat: 37.2493, lon: 27.664, tz: "Europe/Istanbul" },
  { icao: "LTAC", iata: "ESB", name: "Ankara Esenboğa Airport", city: "Ankara", country: "Turkey", lat: 40.1281, lon: 32.9951, tz: "Europe/Istanbul" },
  { icao: "LTCG", iata: "TZX", name: "Trabzon Airport", city: "Trabzon", country: "Turkey", lat: 40.9951, lon: 39.7897, tz: "Europe/Istanbul" },
  { icao: "UKBB", iata: "KBP", name: "Kyiv Boryspil International Airport", city: "Kyiv", country: "Ukraine", lat: 50.345, lon: 30.8947, tz: "Europe/Kyiv" },
  { icao: "UKKK", iata: "IEV", name: "Kyiv Igor Sikorsky Airport", city: "Kyiv", country: "Ukraine", lat: 50.4019, lon: 30.4519, tz: "Europe/Kyiv" },
  { icao: "UKLL", iata: "LWO", name: "Lviv Danylo Halytskyi International Airport", city: "Lviv", country: "Ukraine", lat: 49.8125, lon: 23.9561, tz: "Europe/Kyiv" },
  { icao: "UKOO", iata: "ODS", name: "Odesa International Airport", city: "Odesa", country: "Ukraine", lat: 46.4272, lon: 30.6726, tz: "Europe/Kyiv" },
  { icao: "UKDD", iata: "DNK", name: "Dnipro International Airport", city: "Dnipro", country: "Ukraine", lat: 48.3572, lon: 35.1006, tz: "Europe/Kyiv" },
  { icao: "EGLL", iata: "LHR", name: "London Heathrow Airport", city: "London", country: "United Kingdom", lat: 51.4707, lon: -0.4599, tz: "Europe/London" },
  { icao: "EGKK", iata: "LGW", name: "London Gatwick Airport", city: "London", country: "United Kingdom", lat: 51.1487, lon: -0.1857, tz: "Europe/London" },
  { icao: "EGGW", iata: "LTN", name: "London Luton Airport", city: "London", country: "United Kingdom", lat: 51.8747, lon: -0.3683, tz: "Europe/London" },
  { icao: "EGSS", iata: "STN", name: "London Stansted Airport", city: "London", country: "United Kingdom", lat: 51.885, lon: 0.235, tz: "Europe/London" },
  { icao: "EGLC", iata: "LCY", name: "London City Airport", city: "London", country: "United Kingdom", lat: 51.5053, lon: 0.0553, tz: "Europe/London" },
  { icao: "EGPH", iata: "EDI", name: "Edinburgh Airport", city: "Edinburgh", country: "United Kingdom", lat: 55.9501, lon: -3.3723, tz: "Europe/London" },
  { icao: "EGPF", iata: "GLA", name: "Glasgow Airport", city: "Glasgow", country: "United Kingdom", lat: 55.8719, lon: -4.4331, tz: "Europe/London" },
  { icao: "EGFF", iata: "CWL", name: "Cardiff Wales Airport", city: "Cardiff", country: "United Kingdom", lat: 51.3967, lon: -3.3433, tz: "Europe/London" },
  { icao: "EGNX", iata: "EMA", name: "East Midlands Airport", city: "Nottingham", country: "United Kingdom", lat: 52.8311, lon: -1.3281, tz: "Europe/London" },
  { icao: "EGCC", iata: "MAN", name: "Manchester Airport", city: "Manchester", country: "United Kingdom", lat: 53.3494, lon: -2.2795, tz: "Europe/London" },
  { icao: "EGGP", iata: "LPL", name: "Liverpool John Lennon Airport", city: "Liverpool", country: "United Kingdom", lat: 53.3349, lon: -2.8496, tz: "Europe/London" },
  { icao: "EGNM", iata: "LBA", name: "Leeds Bradford Airport", city: "Leeds", country: "United Kingdom", lat: 53.8659, lon: -1.6606, tz: "Europe/London" },
  { icao: "EGBB", iata: "BHX", name: "Birmingham Airport", city: "Birmingham", country: "United Kingdom", lat: 52.4539, lon: -1.748, tz: "Europe/London" },
  { icao: "EGNT", iata: "NCL", name: "Newcastle Airport", city: "Newcastle", country: "United Kingdom", lat: 55.038, lon: -1.6896, tz: "Europe/London" },
  { icao: "EGHI", iata: "SOU", name: "Southampton Airport", city: "Southampton", country: "United Kingdom", lat: 50.9503, lon: -1.3568, tz: "Europe/London" },
  { icao: "EGHH", iata: "BOH", name: "Bournemouth Airport", city: "Bournemouth", country: "United Kingdom", lat: 50.7805, lon: -1.8396, tz: "Europe/London" },
  { icao: "EGTE", iata: "EXT", name: "Exeter International Airport", city: "Exeter", country: "United Kingdom", lat: 50.7343, lon: -3.414, tz: "Europe/London" },
  { icao: "EGHQ", iata: "NQY", name: "Newquay Cornwall Airport", city: "Newquay", country: "United Kingdom", lat: 50.4406, lon: -4.9954, tz: "Europe/London" },
  { icao: "EGPD", iata: "ABZ", name: "Aberdeen Airport", city: "Aberdeen", country: "United Kingdom", lat: 57.2019, lon: -2.1978, tz: "Europe/London" },
  { icao: "EGPE", iata: "INV", name: "Inverness Airport", city: "Inverness", country: "United Kingdom", lat: 57.5425, lon: -4.0475, tz: "Europe/London" },
  { icao: "EGPO", iata: "SYY", name: "Stornoway Airport", city: "Stornoway", country: "United Kingdom", lat: 58.2156, lon: -6.3311, tz: "Europe/London" },
  { icao: "EGPK", iata: "PIK", name: "Glasgow Prestwick Airport", city: "Glasgow", country: "United Kingdom", lat: 55.5015, lon: -4.5772, tz: "Europe/London" },
  { icao: "EGNJ", iata: "HUY", name: "Humberside Airport", city: "Humberside", country: "United Kingdom", lat: 53.5762, lon: -0.3495, tz: "Europe/London" },
  { icao: "EGAE", iata: "LDY", name: "City of Derry Airport", city: "Derry", country: "United Kingdom", lat: 55.0428, lon: -7.1611, tz: "Europe/London" },
  { icao: "EGAA", iata: "BFS", name: "Belfast International Airport", city: "Belfast", country: "United Kingdom", lat: 54.6575, lon: -6.2158, tz: "Europe/London" },
  { icao: "EGAC", iata: "BHD", name: "George Best Belfast City Airport", city: "Belfast", country: "United Kingdom", lat: 54.6181, lon: -5.8725, tz: "Europe/London" },
  { icao: "EGNS", iata: "IOM", name: "Isle of Man Airport", city: "Isle of Man", country: "United Kingdom", lat: 54.0831, lon: -4.6239, tz: "Europe/Isle_of_Man" },
  { icao: "EGJB", iata: "GCI", name: "Guernsey Airport", city: "Guernsey", country: "United Kingdom", lat: 49.435, lon: -2.602, tz: "Europe/Guernsey" },
  { icao: "EGJJ", iata: "JER", name: "Jersey Airport", city: "Jersey", country: "United Kingdom", lat: 49.2079, lon: -2.1955, tz: "Europe/Jersey" },
  { icao: "UMMS", iata: "MSQ", name: "Minsk National Airport", city: "Minsk", country: "Belarus", lat: 53.8881, lon: 28.04, tz: "Europe/Minsk" },
  { icao: "LATI", iata: "TIA", name: "Tirana Nënë Tereza International Airport", city: "Tirana", country: "Albania", lat: 41.4147, lon: 19.7206, tz: "Europe/Tirane" },
  { icao: "KJFK", iata: "JFK", name: "John F. Kennedy International Airport", city: "New York", country: "United States", lat: 40.6394, lon: -73.7793, tz: "America/New_York" },
  { icao: "KLAX", iata: "LAX", name: "Los Angeles International Airport", city: "Los Angeles", country: "United States", lat: 33.9425, lon: -118.408, tz: "America/Los_Angeles" },
  { icao: "KORD", iata: "ORD", name: "O'Hare International Airport", city: "Chicago", country: "United States", lat: 41.9786, lon: -87.9048, tz: "America/Chicago" },
  { icao: "KATL", iata: "ATL", name: "Hartsfield–Jackson Atlanta International", city: "Atlanta", country: "United States", lat: 33.6367, lon: -84.4281, tz: "America/New_York" },
  { icao: "KSFO", iata: "SFO", name: "San Francisco International Airport", city: "San Francisco", country: "United States", lat: 37.6198, lon: -122.3748, tz: "America/Los_Angeles" },
  { icao: "KDFW", iata: "DFW", name: "Dallas/Fort Worth International Airport", city: "Dallas", country: "United States", lat: 32.8968, lon: -97.038, tz: "America/Chicago" },
  { icao: "KMIA", iata: "MIA", name: "Miami International Airport", city: "Miami", country: "United States", lat: 25.796, lon: -80.2898, tz: "America/New_York" },
  { icao: "VHHH", iata: "HKG", name: "Hong Kong International Airport", city: "Hong Kong", country: "China", lat: 22.3118, lon: 113.9149, tz: "Asia/Hong_Kong" },
  { icao: "RJTT", iata: "HND", name: "Tokyo Haneda Airport", city: "Tokyo", country: "Japan", lat: 35.5497, lon: 139.787, tz: "Asia/Tokyo" },
  { icao: "RJAA", iata: "NRT", name: "Narita International Airport", city: "Tokyo", country: "Japan", lat: 35.7686, lon: 140.3887, tz: "Asia/Tokyo" },
  { icao: "WSSS", iata: "SIN", name: "Singapore Changi Airport", city: "Singapore", country: "Singapore", lat: 1.3502, lon: 103.994, tz: "Asia/Singapore" },
  { icao: "OMDB", iata: "DXB", name: "Dubai International Airport", city: "Dubai", country: "UAE", lat: 25.2498, lon: 55.371, tz: "Asia/Dubai" },
  { icao: "YSSY", iata: "SYD", name: "Sydney Kingsford Smith Airport", city: "Sydney", country: "Australia", lat: -33.9461, lon: 151.177, tz: "Australia/Sydney" },
  { icao: "CYYZ", iata: "YYZ", name: "Toronto Pearson International Airport", city: "Toronto", country: "Canada", lat: 43.6759, lon: -79.6294, tz: "America/Toronto" },
  { icao: "SBGR", iata: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo", country: "Brazil", lat: -23.4313, lon: -46.47, tz: "America/Sao_Paulo" },
  { icao: "FAOR", iata: "JNB", name: "O.R. Tambo International Airport", city: "Johannesburg", country: "South Africa", lat: -26.1401, lon: 28.2468, tz: "Africa/Johannesburg" },
  { icao: "VIDP", iata: "DEL", name: "Indira Gandhi International Airport", city: "New Delhi", country: "India", lat: 28.5556, lon: 77.0952, tz: "Asia/Kolkata" },
  { icao: "ZBAA", iata: "PEK", name: "Beijing Capital International Airport", city: "Beijing", country: "China", lat: 40.0773, lon: 116.5967, tz: "Asia/Shanghai" },
  { icao: "ZSPD", iata: "PVG", name: "Shanghai Pudong International Airport", city: "Shanghai", country: "China", lat: 31.1434, lon: 121.805, tz: "Asia/Shanghai" },
  { icao: "RKSI", iata: "ICN", name: "Incheon International Airport", city: "Seoul", country: "South Korea", lat: 37.4691, lon: 126.451, tz: "Asia/Seoul" },
  { icao: "UUEE", iata: "SVO", name: "Sheremetyevo International Airport", city: "Moscow", country: "Russia", lat: 55.9769, lon: 37.4112, tz: "Europe/Moscow" },
  { icao: "MMMX", iata: "MEX", name: "Mexico City International Airport", city: "Mexico City", country: "Mexico", lat: 19.4358, lon: -99.0703, tz: "America/Mexico_City" },
];

export default AIRPORTS;
