const AIRPORTS = [
  { icao: "KLAX", iata: "LAX", name: "Los Angeles International Airport",          city: "Los Angeles",   country: "United States", lat: 33.9425,  lon: -118.408,  tz: "America/Los_Angeles" },
  { icao: "KJFK", iata: "JFK", name: "John F. Kennedy International Airport",      city: "New York",      country: "United States", lat: 40.6398,  lon: -73.7789,  tz: "America/New_York" },
  { icao: "KORD", iata: "ORD", name: "O'Hare International Airport",               city: "Chicago",       country: "United States", lat: 41.9742,  lon: -87.9073,  tz: "America/Chicago" },
  { icao: "KATL", iata: "ATL", name: "Hartsfield–Jackson Atlanta International",   city: "Atlanta",       country: "United States", lat: 33.6367,  lon: -84.4281,  tz: "America/New_York" },
  { icao: "KSFO", iata: "SFO", name: "San Francisco International Airport",        city: "San Francisco", country: "United States", lat: 37.619,   lon: -122.3748, tz: "America/Los_Angeles" },
  { icao: "KDFW", iata: "DFW", name: "Dallas/Fort Worth International Airport",    city: "Dallas",        country: "United States", lat: 32.8998,  lon: -97.0403,  tz: "America/Chicago" },
  { icao: "KMIA", iata: "MIA", name: "Miami International Airport",                city: "Miami",         country: "United States", lat: 25.7959,  lon: -80.2870,  tz: "America/New_York" },
  { icao: "EGLL", iata: "LHR", name: "London Heathrow Airport",                   city: "London",        country: "United Kingdom", lat: 51.4775, lon: -0.4614,   tz: "Europe/London" },
  { icao: "LFPG", iata: "CDG", name: "Charles de Gaulle Airport",                 city: "Paris",         country: "France",        lat: 49.0097,  lon: 2.5479,    tz: "Europe/Paris" },
  { icao: "EDDF", iata: "FRA", name: "Frankfurt Airport",                          city: "Frankfurt",     country: "Germany",       lat: 50.0379,  lon: 8.5622,    tz: "Europe/Berlin" },
  { icao: "EHAM", iata: "AMS", name: "Amsterdam Airport Schiphol",                city: "Amsterdam",     country: "Netherlands",   lat: 52.3105,  lon: 4.7683,    tz: "Europe/Amsterdam" },
  { icao: "LEMD", iata: "MAD", name: "Adolfo Suárez Madrid–Barajas Airport",      city: "Madrid",        country: "Spain",         lat: 40.4719,  lon: -3.5626,   tz: "Europe/Madrid" },
  { icao: "LIRF", iata: "FCO", name: "Leonardo da Vinci–Fiumicino Airport",       city: "Rome",          country: "Italy",         lat: 41.8003,  lon: 12.2389,   tz: "Europe/Rome" },
  { icao: "LSZH", iata: "ZRH", name: "Zurich Airport",                            city: "Zurich",        country: "Switzerland",   lat: 47.4647,  lon: 8.5492,    tz: "Europe/Zurich" },
  { icao: "VHHH", iata: "HKG", name: "Hong Kong International Airport",           city: "Hong Kong",     country: "China",         lat: 22.3080,  lon: 113.9185,  tz: "Asia/Hong_Kong" },
  { icao: "RJTT", iata: "HND", name: "Tokyo Haneda Airport",                      city: "Tokyo",         country: "Japan",         lat: 35.5494,  lon: 139.7798,  tz: "Asia/Tokyo" },
  { icao: "RJAA", iata: "NRT", name: "Narita International Airport",              city: "Tokyo",         country: "Japan",         lat: 35.7647,  lon: 140.3864,  tz: "Asia/Tokyo" },
  { icao: "WSSS", iata: "SIN", name: "Singapore Changi Airport",                  city: "Singapore",     country: "Singapore",     lat: 1.3644,   lon: 103.9915,  tz: "Asia/Singapore" },
  { icao: "OMDB", iata: "DXB", name: "Dubai International Airport",               city: "Dubai",         country: "UAE",           lat: 25.2532,  lon: 55.3657,   tz: "Asia/Dubai" },
  { icao: "YSSY", iata: "SYD", name: "Sydney Kingsford Smith Airport",            city: "Sydney",        country: "Australia",     lat: -33.9461, lon: 151.1772,  tz: "Australia/Sydney" },
  { icao: "CYYZ", iata: "YYZ", name: "Toronto Pearson International Airport",     city: "Toronto",       country: "Canada",        lat: 43.6772,  lon: -79.6306,  tz: "America/Toronto" },
  { icao: "SBGR", iata: "GRU", name: "São Paulo/Guarulhos International Airport", city: "São Paulo",     country: "Brazil",        lat: -23.4356, lon: -46.4731,  tz: "America/Sao_Paulo" },
  { icao: "FAOR", iata: "JNB", name: "O.R. Tambo International Airport",          city: "Johannesburg",  country: "South Africa",  lat: -26.1392, lon: 28.2460,   tz: "Africa/Johannesburg" },
  { icao: "VIDP", iata: "DEL", name: "Indira Gandhi International Airport",       city: "New Delhi",     country: "India",         lat: 28.5665,  lon: 77.1031,   tz: "Asia/Kolkata" },
  { icao: "ZBAA", iata: "PEK", name: "Beijing Capital International Airport",     city: "Beijing",       country: "China",         lat: 40.0799,  lon: 116.6031,  tz: "Asia/Shanghai" },
  { icao: "ZSPD", iata: "PVG", name: "Shanghai Pudong International Airport",     city: "Shanghai",      country: "China",         lat: 31.1434,  lon: 121.8052,  tz: "Asia/Shanghai" },
  { icao: "RKSI", iata: "ICN", name: "Incheon International Airport",             city: "Seoul",         country: "South Korea",   lat: 37.4691,  lon: 126.4505,  tz: "Asia/Seoul" },
  { icao: "UUEE", iata: "SVO", name: "Sheremetyevo International Airport",        city: "Moscow",        country: "Russia",        lat: 55.9736,  lon: 37.4125,   tz: "Europe/Moscow" },
  { icao: "LTFM", iata: "IST", name: "Istanbul Airport",                          city: "Istanbul",      country: "Turkey",        lat: 41.2608,  lon: 28.7418,   tz: "Europe/Istanbul" },
  { icao: "MMMX", iata: "MEX", name: "Mexico City International Airport",         city: "Mexico City",   country: "Mexico",        lat: 19.4361,  lon: -99.0719,  tz: "America/Mexico_City" },
  { icao: "LOWK", iata: "KLU", name: "Klagenfurt Airport",                        city: "Klagenfurt",    country: "Austria",       lat: 46.6425,  lon: 14.3376,   tz: "Europe/Vienna" },
];

module.exports = AIRPORTS;
